


Condition_numbers.py:

Got a Segmentation fault at first, used 

ulimit -s 20000,

to increase the stack allocated to the python process. Originally, the output of ulimit -s was 8192.
